[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "webresource"
version = "1.3.dev0"
description = "A resource registry for web applications."
readme = {file = "README.rst", content-type = "text/x-rst"}
keywords = ["web", "resources", "dependencies", "javascript", "CSS"]
authors = [{name = "Conestack Constributors", email = "dev@conestack.org"}]
license = {text = "Simplified BSD"}
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Environment :: Web Environment",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: BSD License",
    "Operating System :: OS Independent",
    "Programming Language :: Python",
    "Programming Language :: Python :: 2.7",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Topic :: Internet :: WWW/HTTP :: Dynamic Content",
]

[project.optional-dependencies]
docs = [
    "Sphinx",
    "sphinx_conestack_theme",
]
test = [
    "coverage",
]

[project.urls]
Documentation = "https://webresource.readthedocs.io/"
ChangeLog = "https://github.com/conestack/webresource/blob/master/CHANGES.rst"
"Issue Tracker" = "https://github.com/conestack/webresource/issues"
"Source Code" = "https://github.com/conestack/webresource"

[tool.setuptools]
packages = ["webresource"]
include-package-data = true

[tool.zest-releaser]
create-wheel = true
